pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                app = docker.build("simple-webapp-flask")
            }
        }
        stage('Deploy') {
            steps {
                app = docker.run("simple-webapp-flask")
            }
        }
    }
}
