pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t simple-webapp-flask:latest .'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 simple-webapp-flask:latest'
            }
        }
    }
}
