pipeline {
    agent { dockerfile true }

    stages {
        stage('Build') {
            steps {
                script {
                    dockerImage = docker.build("simple-webapp-flask")
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    dockerContainer = docker.run("simple-webapp-flask")
                }
            }
        }
    }
}
